server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: client_DB
      auto-index-creation: true

application-version: 1.1
